name: "Jest Unit Test Action"
description: "Jestでユニットテストを実行するアクション"
inputs:
  node-version:
    default: '18'
    required: false
    description: 'use nodejs version'

runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup Node.js"
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Run install
      run: npm ci
      shell: bash

    - name: Run test
      run: npm test
      shell: bash
