name: Test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm test
