name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run install
        run: npm ci

      - name: Run test
        run: npm test
